site_name: TechDocs Style Guide
site_url: 
use_directory_urls: false

theme:
  name: material
  palette:
    - scheme: custom-blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: custom-blue-dark
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  logo: assets/nordic_logo.png
  favicon: assets/nordic_logo.png
  features:
    - content.code.annotate
    - content.tooltips
    - content.tabs.link
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - search.highlight
    - toc.follow

extra_css:
  - stylesheets/style.css

copyright:
  Copyright &copy; Nordic Semiconductor 2024

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - meta
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - toc:
      permalink: true
      toc_depth: 4

plugins:
  - macros
  - search

extra:
  test: This is a test abbreviation snippet

nav:
  - Home: README.md
  - Acronyms: acronyms.md
  - Bias-free communication: bias-free-communication.md
  - Capitalization: capitalization.md
  - Glossary: glossary.md
  - Grammar and parts of speech:
    - Dangling and misplaced modifiers: grammar/dangling-misplaced-modifiers.md
    - Grammar tips: grammar/grammar-tips.md
    - Nouns and pronouns: grammar/nouns-pronouns.md
    - Person: grammar/person.md
    - Prepositions: grammar/prepositions.md
    - Verbs: grammar/verbs.md
    - Words ending in -ing: grammar/ing-words.md
  - Numbers: numbers.md
  - Planning:
    - Content planning: planning/content-planning.md
    - Design planning: planning/design-planning.md
    - Final publishing review: planning/final-publishing-review.md
    - Responsive content: planning/responsive-content.md
    - Search and writing: planning/search-writing.md
  - Punctuation:
    - Formatting punctuation: punctuation/formatting-punctuation.md
    - Apostrophes: punctuation/apostrophes.md
    - Colons: punctuation/colons.md
    - Commas: punctuation/commas.md
    - Dashes and hyphens: punctuation/dashes-and-hyphens.md
    - Ellipses: punctuation/ellipses.md
    - Exclamation points: punctuation/exclamation-points.md
    - Periods: punctuation/periods.md
    - Quotation marks: punctuation/quotation-marks.md
    - Semicolons: punctuation/semicolons.md
    - Slashes: punctuation/slashes.md
    - Square brackets: punctuation/square-brackets.md
  - Text formatting:
    - Code examples: text-formatting/code-examples.md
    - General formatting: text-formatting/general-formatting.md
    - Typographic conventions: text-formatting/typographic-conventions.md
    - URLs and web addresses: text-formatting/urls-web-addresses.md
  - Trademarks: trademarks.md
  - Units of measurement: units-of-measurement.md
  - Word choice: word-choice.md
  - Writing tips:
      - Accessibility tips: writing-tips/accessibility.md
      - Jargon: writing-tips/jargon.md
      - Simple writing: writing-tips/simple-writing.md
  # - Procedures and instructions:
  #   - Procedures and instructions: procedures-instructions/index.md
  #   - Writing step-by-step instructions: procedures-instructions/writing-step-by-step-instructions.md
  #   - Describing interactions with UI: procedures-instructions/describing-interactions-with-ui.md
  #   - Describing alternative input methods: procedures-instructions/describing-alternative-input-methods.md
  #   - Formatting text in instructions: procedures-instructions/formatting-text-in-instructions.md
  #   - Illustrating network traffic flows: procedures-instructions/illustrating-network-traffic-flows.md
  # - Scannable content:
  #   - Scannable content: scannable-content/index.md
  #   - Headings: scannable-content/headings.md
  #   - Lists: scannable-content/lists.md
  #   - Pull quotes: scannable-content/pull-quotes.md
  #   - Sidebars: scannable-content/sidebars.md
  #   - Tables: scannable-content/tables.md
